const ALBUMS = [
  {
    title: "GODHAND VOLUME 0",
    cover: "/albums/0.jpg",
    id: "7CW4FfVZu66BPrBrq5buza",
    releaseDate: Date.parse("31 Aug 2024 00:00:00 PDT"),
    tracks: [
      {
        trackNo: 1,
        title: "THOUGHT HE WUZ",
        durationMS: 137294,
        id: "59QHRjUcxKLNHpFvecti67",
      },
      {
        trackNo: 2,
        title: "FINGER ON THE TRIGGER",
        durationMS: 131600,
        id: "30y7xL0vIr8tVxRIKlhiNQ",
      },
      {
        trackNo: 3,
        title: "GODHAND",
        durationMS: 172125,
        id: "7MW7F3KGWcMHWPow6V6NMD",
      },
      {
        trackNo: 4,
        title: "RIDIN' IN THE WHIP",
        durationMS: 142822,
        id: "2n2R1ssPRU6Jmp3NL86jwV",
      },
      {
        trackNo: 5,
        title: "SADHAND",
        durationMS: 117692,
        id: "6jjcizLFBX82M5RlBFrGS8",
      },
      {
        trackNo: 6,
        title: "WE DOIN' FINE",
        durationMS: 133333,
        id: "5X1jnV9C1v5efKoUl0pKxo",
      },
      {
        trackNo: 7,
        title: "IN DA BANK",
        durationMS: 129817,
        id: "0tOqCTkPpdruplpOau6Gc7",
      },
      {
        trackNo: 8,
        title: "SHIT THE BED",
        durationMS: 191707,
        id: "6Sk4Osrayu90AtFCDrLUGO",
      },
      {
        trackNo: 9,
        title: "NIGHTMARES",
        durationMS: 138666,
        id: "5Efkd5bBqOZsGKzS34nsqh",
      },
      {
        trackNo: 10,
        title: "MURDA MELODIES",
        durationMS: 217500,
        id: "1GZpXbVErkZLDKC5xpyGfD",
      },
    ],
  },
  {
    title: "GODHAND VOLUME 1",

    id: "1sAr7ylbTfTyPnNT17ZwZI",
    cover: "/albums/1.jpg",
    releaseDate: Date.parse("11 Sep 2024 00:00:00 PDT"),
    tracks: [
      {
        trackNo: 1,
        title: "SALVATION",
        durationMS: 122790,
        id: "5kfKYjz5OHYWYN2iiIvo0g",
      },
      {
        trackNo: 2,
        title: "NEED SUM MO",
        durationMS: 89333,
        id: "3ymUwwiA8nxomHClHPLZNj",
      },
      {
        trackNo: 3,
        title: "εїз ☆ MEMPHIS_SWAG_BOUNCE_REMIX.logicx ☆ εїз",
        durationMS: 118666,
        id: "1zY0NtFgKJuMmpLVJ57wxo",
      },
      {
        trackNo: 4,
        title: "TALKING THAT SMACK",
        durationMS: 137142,
        id: "7aQcdToYbsUhPJUMV1CHQu",
      },
      {
        trackNo: 5,
        title: "SWAGFUNKIN'",
        durationMS: 93090,
        id: "2lODUuaw5Duvj6Lj9sgN4t",
      },
      {
        trackNo: 6,
        title: "9MM (KURT COBAIN)",
        durationMS: 147826,
        id: "6ag61eaQdMrfBf0ceoOOWq",
      },
      {
        trackNo: 7,
        title: "OUTSIDE",
        durationMS: 142588,
        id: "5AmCXqjtfGgBUmBFPhoaIo",
      },
      {
        trackNo: 8,
        title: "UH HUH UH HUH",
        durationMS: 132750,
        id: "30cNfQDDt07ASdopjgMFhM",
      },
      {
        trackNo: 9,
        title: "DI$ SIDE",
        durationMS: 187682,
        id: "2vS0AP8hBF21DMnj4RxkSu",
      },
      {
        trackNo: 10,
        title: "SAVE OUR SOULS",
        durationMS: 126000,
        id: "6dG8t0PlDI9NTktdUpOlp5",
      },
      {
        trackNo: 11,
        title: "HUMAN SACRIFICE",
        durationMS: 131145,
        id: "3rHPVlwOTyrtYRk3rx2JRc",
      },
      {
        trackNo: 12,
        title: "DEVIL IN MY DREAMS",
        durationMS: 216000,
        id: "7lsw4MJvinYJIWqfOOWpw1",
      },
      {
        trackNo: 13,
        title: "WE EATIN' GOOD",
        durationMS: 132000,
        id: "2MlTAFiqW34yfrH3rZENIx",
      },
      {
        trackNo: 14,
        title: "PLAY NO GAMES",
        durationMS: 102400,
        id: "2LJrRWKepzhOC8ZZw0rrnh",
      },
    ],
  },
  {
    title: "GODHAND VOLUME 2",
    id: "0Wvhhn3mHQaBeS9a3M77dX",
    cover: "/albums/2.jpg",
    releaseDate: Date.parse("02 Apr 2025 00:00:00 PDT"),
    tracks: [
      {
        trackNo: 1,
        title: "GIVE PRAISE TO THE HAND",
        durationMS: 113863,
        id: "6jcr6fGyREcZ4lxUZPlMQQ",
      },
      {
        trackNo: 2,
        title: "YEAH HOE",
        durationMS: 107200,
        id: "0fW1tbwbkpHLNSWIKX9226",
      },
      {
        trackNo: 3,
        title: "GET UP!",
        durationMS: 114947,
        id: "0scrUE2WuwQWn0Onz79aGU",
      },
      {
        trackNo: 4,
        title: "HOP OFF THE PORCH",
        durationMS: 181530,
        id: "66wHTyctIjB2DjqpcTcKhd",
      },
      {
        trackNo: 5,
        title: "CALI GOLD",
        durationMS: 200597,
        id: "3jsg4DX3ZK9FcNvfTMXnVj",
      },
      {
        trackNo: 6,
        title: "SMOKE THE WEED",
        durationMS: 158108,
        id: "0sMr0BBUfePOuAgfhlNyf1",
      },
      {
        trackNo: 7,
        title: "HOW YOU AIN'T GOT NO GUN?",
        durationMS: 137294,
        id: "6X3l5ESGl0WCLpNuMXqDBw",
      },
      {
        trackNo: 8,
        title: "POCKETS FULL UH",
        durationMS: 117666,
        id: "0KL6c9zHC748WtE1nYIoW9",
      },
      {
        trackNo: 9,
        title: "YOU KNOW HOW IT GO",
        durationMS: 172800,
        id: "2mYAgYa4SufUXriRsE2AsC",
      },
      {
        trackNo: 10,
        title: "LIVING LIFE FEELS LIKE HELL",
        durationMS: 160416,
        id: "0BlT2NTJwzgdhi4BFl2lnH",
      },
      {
        trackNo: 11,
        title: "INDIGENOUS IMMIGRANT",
        durationMS: 256090,
        id: "0jPHuehnmAKWiqupg68xwl",
      },
      {
        trackNo: 12,
        title: "THE WORLD IS A LIVING HELL",
        durationMS: 169272,
        id: "2gNda6G8188JmQNqzhAWcM",
      },
      {
        trackNo: 13,
        title: "RIDIN' IN THE WHIP PT. 2",
        durationMS: 131200,
        id: "59HqSPzdOuXbvxbVSKyJTI",
      },
      {
        trackNo: 14,
        title: "PUT IT ALL TO REST",
        durationMS: 174681,
        id: "0VKEa0gSIZ7K4u0zTnrXB2",
      },
      {
        trackNo: 15,
        title: "THE DEVIL'S FOOT",
        durationMS: 218871,
        id: "3n1ytMIzO6gEZzhFN4Fobw",
      },
      {
        trackNo: 16,
        title: "STOMP EM OUT",
        durationMS: 130000,
        id: "3lzN7uCAsFPGng0sisafhX",
      },
      {
        trackNo: 17,
        title: "GET YO GIRL PREGNANT",
        durationMS: 124000,
        id: "43Isu2JOelz3yV8gnyUH8R",
      },
      {
        trackNo: 18,
        title: "THUG IT OUT",
        durationMS: 110000,
        id: "2pYNojHL9OX1lI8dDmexeL",
      },
      {
        trackNo: 19,
        title: "AN HOURGLASS IN DEATH'S MAUSOLEUM",
        durationMS: 199000,
        id: "41gVsbcdlctvR7yE58R7vG",
      },
      {
        trackNo: 20,
        title: "IF YOU WANT IT BAD ENOUGH",
        durationMS: 221000,
        id: "6zNuMcmHN3oxqMBGlAp2ga",
      },
    ],
  },
];

export default ALBUMS;
