import type { Metadata } from "next";
import FX from "./fx";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
        precedence="default"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Tektur:wght@400..900&display=swap"
        rel="stylesheet"
        precedence="default"
      />
      <body>
        <FX>{children}</FX>
        {children}
      </body>
    </html>
  );
}
