import type { Metadata } from "next";
import { Share_Tech, Share_Tech_Mono } from "next/font/google";
import FX from "./fx";
import "./globals.css";

const shareTech = Share_Tech({
  variable: "--font-share-tech-sans",
  subsets: ["latin"],
  weight: "400",
});

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${shareTech.variable} ${shareTechMono.variable} antialiased`}
      >
        <FX>{children}</FX>
        {children}
      </body>
    </html>
  );
}
